# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-30 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181130_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(help_text='제품 유형', max_length=100, verbose_name='제품 유형'),
        ),
    ]
