# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-11 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181130_1445'),
        ('blog', '0006_auto_20181130_1509'),
    ]

    operations = [
    ]
