# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_merge_20181211_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='작성자 이름', max_length=100, verbose_name='제품유형'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='제품 유형', unique=True, verbose_name='작성자'),
        ),
    ]
